### ISSUE TITLE
corrupted diacritics in EPG

### ISSUE THREAD

**Issue by rchovan** [openhdf/enigma2#11]
Epg show fonts with wrong diacritics in Slovak language

![image](https://cloud.githubusercontent.com/assets/6713920/20401916/e421a9d4-acfa-11e6-83e5-58033150e4f5.png)

Image openhdf-5.5-xpeedlx3-178-20161111_usb.zip  

I have tried multiple skins, and tried to change font in skins. Result is same error. 

Značka:	GI
Model:	LX-3
Čipset:	bcm7424
Verzia frontprocesora:	20038
Celková pamäť:	1155704 kB
Voľná pamäť:	1019176 kB
Doba prevádzky:	0:01
Softvér
Systém OE:	OE-Alliance 3.4
Distribúcia:	openhdf
Verzia firmvéru:	5.5.178
Dátum ovládačov:	20160120
Verzia jadra:	3.14.2
Verzia GUI:	2016-11-11
Tunery
Tuner A:	DVB-S2 NIM (DVB-S2)
Tuner B:	DVB-S2 NIM (DVB-S2)

**Comment by rchovan** [comment]
please add this to encoding.conf

1105 53	#	SkyLink
3202 3	#	SkyLink
3205 3	#	SkyLink
3207 3	#	SkyLink
3208 3	#	SkyLink
3209 3	#	SkyLink
3211 3	#	SkyLink
3212 3	#	SkyLink
3214 3	#	SkyLink
3217 3	#	SkyLink
3219 3	#	SkyLink
3220 3	#	SkyLink
3221 3	#	SkyLink
3224 3	#	SkyLink
3234 3	#	SkyLink

**Comment by koivo** [comment]
Done
https://github.com/openhdf/enigma2/commit/7962a624d2256d74b1974b30169ed842f84e7700

**Comment by rchovan** [comment]
please add this new transpoder too 
3233 3 # SkyLink
or in this way 
0xca1 0x3 # Astra 23.5E 12.344 V - SkyLink

**Comment by koivo** [comment]
Done
https://github.com/openhdf/enigma2/commit/26ec53dc34966d20cc020efa5d5c2ae612a56b48
