### ISSUE TITLE
crashing when transcoding

### ISSUE THREAD

**Issue by rchovan** [openhdf/enigma2#12]
When I want to transcode service, enigma2 crash

[enigma2_crash_1479406334.txt](https://github.com/openhdf/enigma2/files/598157/enigma2_crash_1479406334.txt)
[enigma2_crash_1479407053.txt](https://github.com/openhdf/enigma2/files/598158/enigma2_crash_1479407053.txt)

___
Image openhdf-5.5-xpeedlx3-178-20161111_usb.zip

Značka:	GI
Model:	LX-3
Čipset:	bcm7424
Verzia frontprocesora:	20038
Celková pamäť:	1155704 kB
Voľná pamäť:	1019176 kB
Doba prevádzky:	0:01
Softvér
Systém OE:	OE-Alliance 3.4
Distribúcia:	openhdf
Verzia firmvéru:	5.5.178
Dátum ovládačov:	20160120
Verzia jadra:	3.14.2
Verzia GUI:	2016-11-11
Tunery
Tuner A:	DVB-S2 NIM (DVB-S2)
Tuner B:	DVB-S2 NIM (DVB-S2)

**Comment by koivo** [comment]
This is a git and not a forum. Please ask your question inside the openhdf forum.
