### ISSUE TITLE
GI LX3, plugin button does not work 

### ISSUE THREAD

**Issue by rchovan** [openhdf/enigma2#15]
Hi, on my GI LX3 button plugin does not work. It show white rectangle on upper right screen. This is my remote control settings:

![image](https://cloud.githubusercontent.com/assets/6713920/21401115/53498782-c7b3-11e6-942b-f4733dd5cfd6.png)

**Comment by koivo** [comment]
This is a git and not a forum. Please ask your question inside the openhdf forum.
