### ISSUE TITLE
installed plugin is missing in plugins

### ISSUE THREAD

**Issue by rchovan** [openhdf/enigma2#16]
I have installed plugin enigma2-plugin-extensions-epgrefresh , but is missing in plugins.  It show after enigma restart. On previous versions, it is visible right after installation.

```
root@xpeedlx3:~# opkg install enigma2-plugin-extensions-epgrefresh
Installing enigma2-plugin-extensions-epgrefresh (2.0+git6210+f16ab52-r10) on root.
Configuring enigma2-plugin-extensions-epgrefresh.
```

![image](https://cloud.githubusercontent.com/assets/6713920/21401263/eb901b82-c7b3-11e6-9d67-0172a21b6405.png)

___
GI LX, OpenHDF 5.5.197 (2016-12-18)

**Comment by koivo** [comment]
I dont't know what happens wit this plugin.
This plugin was developed by another person and not by HDF team.
