### ISSUE TITLE
transcoding does not work and crash enigma

### ISSUE THREAD

**Issue by rchovan** [openhdf/enigma2#17]
Transcoding does not work and it crash enigma2. 

I have debug enabled, so here are debug logs:
[e2crash.zip](https://github.com/openhdf/enigma2/files/672259/e2crash.zip)

My stb is GI Xpeed LX3
Systém OE:	OE-Alliance 3.4
Firmware:	OpenHDF 5.5.197 (2016-12-18)
Kernel / Drivers:	3.14.2 / 20160120

**Comment by koivo** [comment]
I can see an errormessage with timeshift and fixed this now.
But the crash was caused by wrong or corrupt epg cache data.
