### ISSUE TITLE
Hdmi cec commands

### ISSUE THREAD

**Issue by sunder67** [openhdf/enigma2#27]
It opens the menu on the 3 buttons on the TV remote control
![55puk6400](https://cloud.githubusercontent.com/assets/11820090/25583721/b1706de0-2e9b-11e7-84e4-2fd260a5f2ba.jpg)
Button 1 >  info = opening the menu
Button 2 >  text = opening the menu
Button 3 >  subtitle = opening the menu
Expected: "subtitle" and "text" buttons perform other functions

Tv: Philips 55puk6400

**Comment by koivo** [comment]
Ok thanks for information, but we cannot do anythink. Its a Philips problem and theyre non correct cec support.
