### ISSUE TITLE
non-localizable section

### ISSUE THREAD

**Issue by sunder67** [openhdf/enigma2#34]
Cannot translate the time remaining on the current event
![ss](https://user-images.githubusercontent.com/11820090/47962714-e4b6ba80-e031-11e8-9f07-7b146db6a8d7.png)

**Comment by koivo** [comment]
Can you try another skin?

**Comment by koivo** [comment]
Have you try %d Min or %d Mins ?

**Comment by sunder67** [comment]
> Have you try %d Min or %d Mins ?

strings in the translation file

msgid "%d Min"
msgid_plural "%d Mins"
msgstr[0] "%d Dak"
msgstr[1] "%d Dak"

msgid "%d min"
msgstr "%d dak"

msgid "%s%d min"
msgstr "%s%d dak"

msgid "Mins"
msgstr "Dak"

msgid "mins"
msgstr "dak"

msgid "min"
msgstr "dak"

**Comment by koivo** [comment]
I have changes the converter in the skin and it works now.
Works with next update. Do you have try it with another skin?

**Comment by sunder67** [comment]
![dmconcinnity-hdss1](https://user-images.githubusercontent.com/11820090/47985971-5eab7a00-e0ec-11e8-89f5-8503d6b8b010.png)
dmconcinnity-hd 
![4hdf_2_2_speedy_modss2](https://user-images.githubusercontent.com/11820090/47986000-6ff48680-e0ec-11e8-8433-ccf40c03cd18.png)
4hdf_2_2_speedy_mod 
![xionhdf](https://user-images.githubusercontent.com/11820090/47988874-6f5fee00-e0f4-11e8-8dbe-aefd42ca3173.png)
xionHDF

**Comment by koivo** [comment]
Looks good, wait for the next update and Xion is also fixed.

**Comment by sunder67** [comment]
There are a few more places
-2nd information bar
-channel list

**Comment by koivo** [comment]
I hope this is fixed now at all positions https://github.com/KravenHD/XionHDF/commit/e4f74947193c53b44b866891ed3e2c87b0fc6fe5
