### ISSUE TITLE
weather in German

### ISSUE THREAD

**Issue by sunder67** [openhdf/enigma2#36]
weather notifications looks in German

![image](https://user-images.githubusercontent.com/11820090/49632168-d29bb380-fa05-11e8-849b-fd94158d573b.jpg)

**Comment by koivo** [comment]
Xion don't have an english translation.
The translations are missing in XionHDF.po inside locale tr folder.

**Comment by koivo** [comment]
https://github.com/KravenHD/XionHDF/commit/242f65269c3781a7710e35f0e0006d6c7c6d5387
This commit used now the selected language from image.
