### ISSUE TITLE
corrupted font characters

### ISSUE THREAD

**Issue by sunder67** [openhdf/enigma2#37]
weather in the left corner is corrupted

![image1](https://user-images.githubusercontent.com/11820090/49689033-0bce4380-fb2c-11e8-9277-d21e0b75210d.jpg)
![image2](https://user-images.githubusercontent.com/11820090/49689036-112b8e00-fb2c-11e8-81d4-746353c9efee.jpg)
![image3](https://user-images.githubusercontent.com/11820090/49689039-1a1c5f80-fb2c-11e8-96d8-314e49381f39.jpg)

**Comment by koivo** [comment]
This test was received from https://www.accuweather.com
If the website shows correct informations, there must be a problem with font or enconding.
I cannot read this.

**Comment by sunder67** [comment]
this problem is only in the left corner
![image1](https://user-images.githubusercontent.com/11820090/49689963-4a6afa80-fb3a-11e8-86dd-4578f86de49e.jpg)

**Comment by koivo** [comment]
Have you tried the other weather options? All the same?

**Comment by sunder67** [comment]
current status 
just left corner this way
![image4](https://user-images.githubusercontent.com/11820090/49690261-e72f9700-fb3e-11e8-94f6-97d438c55f3c.jpg)

**Comment by sunder67** [comment]
Turkish UTF-8 character sequence
https://github.com/KravenHD/XionHDF/pull/10
