### ISSUE TITLE
Why using openhdf image the booting time more longer ?

### ISSUE THREAD

**Issue by opfans** [openhdf/enigma2#39]
My receiver is octagon sf4008 with  openhdf image.i have question that when it boot ,it will spent a long time .it boot much slow from turning on  to displaying  the program.when it used openatv ,booting more faster then used openhdf.i dont know why .it will take 32 seconds using openatv ,take approximately 63 seconds  more using openhdf when booting.can openhdf team fix the issue.

**Comment by koivo** [comment]
This is not a support forum and by the way ... my sf4008 needs 45 seconds for a complete start.
And i have installed a lot of plugins , iptv online updates and an NAS mounted.
