### ISSUE TITLE
view cavs stream serviceInfo,enigma2 crash

### ISSUE THREAD

**Issue by opfans** [openhdf/enigma2#40]
When view  cavs (it is a video compression standard,just like hevc)serviceinfo,enigma2 crash and restart gui.
I check the file  ServiceInfo.py on https://github.com/openhdf/enigma2/blob/master/lib/python/Screens/ServiceInfo.py,
add "H265", "CAVS" on line 148 videocodec,can fix this issue.see below:videocodec =  ("MPEG2", "MPEG4", "MPEG1", "MPEG4-II", "VC1", "VC1-SM", "HEVC", "H265", "CAVS", "-" ),can openhdf team add this ,i know openatv  has fixed this issue.

**Comment by koivo** [comment]
Thanks for feedback.
I have merged this screen from openatv,
https://github.com/openhdf/enigma2/commit/a1c181de1e18391c4b312dddacd6f8d007e04ed2
