### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by elhawaryna** [openhdf/enigma2#47]
openhdf 7.0 dm820

dm820 login: root
root@dm820:~# init 4
root@dm820:~# ENIGMA_DEBUG_LVL=4 enigma2
PYTHONPATH: /usr/lib/enigma2/python
DVB_API_VERSION 5 DVB_API_VERSION_MINOR 11
ENIGMA_DEBUG_LVL=4
[Avahi] avahi_timeout_new
[Avahi] avahi_watch_new(3 0x1)
[Avahi] avahi_timeout_update
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] client state: 2
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[eInit] + (1) Background File Eraser
[eInit] + (5) Tuxtxt
[eInit] + (8) graphics acceleration manager
[eInit] + (9) Font Render Class
[Font] Initializing lib.
[Font] Loading fonts.
[Font] Intializing font cache, using max. 4MB.
[eInit] + (9) gLCD
[eFbLCD] /dev/fb1 No such file or directory
[eFbLCD] framebuffer /dev/fb1 not available
[eLCD] found OLED display!
[eDboxLCD] xres=96, yres=64, bpp=16 lcd_type=3
[eLCD] (96x64x16) buffer 0xccda68 12288 bytes, stride 192, boxtype: dm820

[gLCDDC] resolution: 96 x 64 x 16 (stride: 192)
[eInit] + (9) GFBDC
[fb] /dev/fb0: 3600k video mem
[fb] Using ION allocator
[fb] 32768kB available for acceleration surfaces (via ION).
[fb] double buffering available!
[fb] 2 page(s) available!
[gFBDC] resolution: 1280 x 720 x 32 (stride: 5120) pages: 2
[eInit] + (10) gRC
[gRC] thread created successfully
[eInit] + (15) eWindowStyleManager
[eInit] + (20) AVSwitch Driver
[eAVSwitch] failed to open /dev/dbox/fp0 to monitor vcr scart slow blanking changed: No such file or directory
[eInit] + (20) misc options
[eInit] + (20) RC Input layer
[eInit] + (20) UHF Modulator
[eRFmod] couldnt open /dev/rfmod0: No such file or directory
[eInit] + (20) DVB-CI UI
[eInit] + (21) input device driver
[eInputDeviceInit] adding device /dev/input/event0
[eRCInputEventDriver] devicename=dreambox front panel
[eRCDeviceInputDev] device "dreambox front panel" is a remotecontrol
[eInputDeviceInit] adding device /dev/input/event1
[eRCInputEventDriver] devicename=dreambox remote control (native)
[eRCDeviceInputDev] device "dreambox remote control (native)" is a remotecontrol
[eInputDeviceInit] adding device /dev/input/event2
[eRCInputEventDriver] devicename=dreambox advanced remote control (native)
[eRCDeviceInputDev] device "dreambox advanced remote control (native)" is a remotecontrol
[eInputDeviceInit] adding device /dev/input/event3
[eRCInputEventDriver] devicename=dreambox ir keyboard
[eRCDeviceInputDev] device "dreambox ir keyboard" is a keyboard
[eInputDeviceInit] adding device /dev/input/event4
[eRCInputEventDriver] devicename=dreambox ir mouse
[eRCDeviceInputDev] device "dreambox ir mouse" is a mouse
[eInputDeviceInit] adding device /dev/input/event5
[eRCInputEventDriver] devicename=dreambox remote control (bluetooth le)
[eRCDeviceInputDev] device "dreambox remote control (bluetooth le)" is a remotecontrol
[eInputDeviceInit] Found 6 input devices.
[eInit] + (22) Hdmi CEC driver
[eHdmiCEC] detected physical address change: 1000 --> 3000
[eHdmiCEC] send message 0F 84 30 00 03
[eInit] + (30) eActionMap
[eInit] + (35) CA handler
[eInit] + (35) CI Slots
[CI] scanning for common interfaces..
[CI] done, found 0 common interface slots
[eInit] + (40) eServiceCenter
[eServiceCenter] settings instance.
[eInit] + (41) Stream server
[Avahi] AvahiServiceEntry (null) (_e2stream._tcp) 8001
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] Will Register dm820 (_e2stream._tcp) on dm820:8001
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] Registered dm820 (_e2stream._tcp) on dm820:8001

[eInit] + (41) RTSP Stream server
[eInit] + (41) Encoders
[eInit] + (41) eServiceFactoryDVB
[eInit] + (41) eServiceFactoryFS
[eInit] + (41) eServiceFactoryMP3
[eInit] + (41) eServiceFactoryM2TS
[eInit] + (41) eServiceFactoryHDMI
[eInit] + (41) eServiceFactoryTS
[eInit] + (41) eServiceFactoryWebTS
[eInit] + (41) eServiceFactoryDVD
[eInit] reached rl 70
[eDVBDB] ---- opening lame channel db
[eDVBDB] reading services (version 4)
[eDVBDB] loaded 100 channels/transponders and 1398 services
eDVBSatelliteEquipmentControl::clear()
[eDVBResourceManager] scanning for frontends..
[eDVBFrontend] opening frontend 0
[eDVBFrontend] m_need_delivery_system_workaround = 0
[eDVBFrontend] opening frontend 0
frontend 0 setDeliverySystem 17
frontend 0 setDeliverySystem 6
frontend 0 setDeliverySystem 5
[eDVBFrontend] try to close frontend 0
[eDVBAdapterLinux] get demux 0
[eDVBAdapterLinux] get demux 1
[eDVBAdapterLinux] get demux 2
[eDVBAdapterLinux] get demux 3
[eDVBAdapterLinux] get demux 4
[eDVBAdapterLinux] get demux 5
[eDVBAdapterLinux] get demux 6
[eDVBAdapterLinux] get demux 7
[eDVBResourceManager] found 1 adapter, 1 frontends(1 sim) and 8 demux, boxtype 7
[eDVBLocalTimeHandler] RTC not ready... wait for transponder time
[eEPGCache] Initialized EPGCache (wait for setCacheFile call now)
[MAIN] Loading spinners...
[ePNG] couldn't open /etc/enigma2/spinner/wait1.png
[ePNG] couldn't open /usr/share/enigma2/spinner/wait31.png
[MAIN] found 30 spinner!
[MAIN] executing main

[setIoPrio] best-effort level 3 ok
no profile data available
[gRC] main thread is non-idle! display spinner!
[Misc_Options] 12Vdetect cannot open /proc/stb/misc/12V_output: No such file or directory
[Console] command: mount /dev/mmcblk0p1 /tmp/multibootcheck
[eConsoleAppContainer] Starting /bin/sh
[Console] command: umount /tmp/multibootcheck
[eConsoleAppContainer] Starting /bin/sh
[Harddisk] enumerating block devices...
[Harddisk] new Harddisk sda -> /dev/sda -> /dev/sda
[Console] command: ('sdparm', 'sdparm', '--set=SCT=0', '/dev/sda')
[eConsoleAppContainer] Starting sdparm
[Harddisk] enumerating network mounts...
[Geolocation] Geolocation data initialised.
[Keyboard] Adding keymap 'Default (US)' ('default.kmap').
[Keyboard] Adding keymap 'azerty keyboard' ('azerty.kmap').
[Keyboard] Adding keymap 'Dreambox Keyboard English' ('eng.kmap').
[Keyboard] Adding keymap 'Dreambox Keyboard Deutsch' ('dream-de.kmap').
[Keyboard] Adding keymap 'German keyboard' ('de.kmap').
[Keyboard] Activating keymap: 'Dreambox Keyboard Deutsch'.
[Console] command: loadkmap < /usr/share/keymaps/dream-de.kmap
[eConsoleAppContainer] Starting /bin/sh
Activating language Deutsch
[SKIN ERROR] attempt to add a skin without filename
menu_mainmenu
[Picon] adding path: /media/hdd/picon/
Reading satellites.xml
eDVBSatelliteEquipmentControl::clear()
sec config cleared
[eDVBFrontend] setSlotInfo for dvb frontend 0 to slotid 0, descr BCM4505, need rotorworkaround No, enabled Yes, DVB-S2 No
slot: 0 configmode: simple
eDVBSatelliteEquipmentControl::setSlotNotLinked(0)
diseqcmode:  single
sec config completed
[NimManager] slotname = A, slotdescription = BCM4505, multitype = False, current type = DVB-S2
[AVSwitch] reading edid modes failed, using all modes
[AVSwitch] reading _preferred modes:  ['480i', '576i', '1080i', '1080p', '720p', '480p', '1080i50', '1080p50', '720p50', '576p', '640x480', '800x600', '1024x768']
[InfoBarGenerics] Failed to load resumepoints: [Errno 2] No such file or directory: '/etc/enigma2/resumepoints.pkl'
[InfoBarGenerics] Failed to load resumepoints: [Errno 2] No such file or directory: '/etc/enigma2/resumepoints.pkl'
~~~~ read box informations ~~~~~~~~~
MachineName = DM820
MachineBrand = Dreambox
BoxType = dm820
getMachineBuild = dm820
ChipString = 7435
OEM = dreambox
Driverdate = 20181018
Imageversion = 7.0
Imagebuild = 1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[eDVBDB] loading bouquet... /etc/enigma2//bouquets.tv
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.favourites.tv
[eDVBDB] 30 entries in Bouquet userbouquet.favourites.tv
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.bef001.tv
[eDVBDB] 67 entries in Bouquet userbouquet.bef001.tv
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.bef002.tv
[eDVBDB] 35 entries in Bouquet userbouquet.bef002.tv
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.bef003.tv
[eDVBDB] 54 entries in Bouquet userbouquet.bef003.tv
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.bef004.tv
[eDVBDB] 7 entries in Bouquet userbouquet.bef004.tv
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.bef005.tv
[eDVBDB] 12 entries in Bouquet userbouquet.bef005.tv
[eDVBDB] can't open /etc/enigma2/.../userbouquet.bef006.tv: No such file or directory
[eDVBDB] can't load bouquet userbouquet.bef006.tv
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.bef007.tv
[eDVBDB] 26 entries in Bouquet userbouquet.bef007.tv
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.bef008.tv
[eDVBDB] 28 entries in Bouquet userbouquet.bef008.tv
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.bef009.tv
[eDVBDB] 19 entries in Bouquet userbouquet.bef009.tv
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.bef010.tv
[eDVBDB] 9 entries in Bouquet userbouquet.bef010.tv
[eDVBDB] 11 entries in Bouquet bouquets.tv
[eDVBDB] loading bouquet... /etc/enigma2//bouquets.radio
[eDVBDB] loading bouquet... /etc/enigma2//userbouquet.favourites.radio
[eDVBDB] 31 entries in Bouquet userbouquet.favourites.radio
[eDVBDB] can't open /etc/enigma2/.../userbouquet.iptv_radio.radio: No such file or directory
[eDVBDB] can't load bouquet userbouquet.iptv_radio.radio
[eDVBDB] 2 entries in Bouquet bouquets.radio
[eDVBDB] Renumbering...
[Time By]: Transponder
[eEPGCache] time updated.. but cache file not set yet.. dont start epg!!
2022-01-17 09:52:39+0100 [-] Log opened.
2022-01-17 09:52:40+0100 [-] [Ipkg] Added to OPKG destinations: /media/hdd
2022-01-17 09:52:40+0100 [-] [Ipkg] Added to OPKG destinations: /
2022-01-17 09:52:40+0100 [-] Traceback (most recent call last):
2022-01-17 09:52:40+0100 [-]   File "/usr/lib/enigma2/python/mytest.py", line 190, in <module>
2022-01-17 09:52:40+0100 [-]     Screen.global_screen = Globals()
2022-01-17 09:52:40+0100 [-]   File "/usr/lib/enigma2/python/Screens/Globals.py", line 9, in __init__
2022-01-17 09:52:40+0100 [-]     Screen.__init__(self, None)
2022-01-17 09:52:40+0100 [-]   File "/usr/lib/enigma2/python/Screens/Screen.py", line 56, in __init__
2022-01-17 09:52:40+0100 [-]     self.summaries = CList()
2022-01-17 09:52:40+0100 [-] NameError: name 'CList' is not defined
[eDVBDB] ---- saving lame channel db
[eDVBDB] saved 100 channels and 1398 services!
[eDVBResourceManager] release cached channel (timer timeout)
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_watch_free
[Avahi] avahi_timeout_free
[eInit] - (41) Stream server
[eInit] - (41) RTSP Stream server
[eInit] - (41) Encoders
[eInit] - (41) eServiceFactoryDVB
[eInit] - (41) eServiceFactoryFS
[eInit] - (41) eServiceFactoryMP3
[eInit] - (41) eServiceFactoryM2TS
[eInit] - (41) eServiceFactoryHDMI
[eInit] - (41) eServiceFactoryTS
[eInit] - (41) eServiceFactoryWebTS
[eInit] - (41) eServiceFactoryDVD
[eInit] - (40) eServiceCenter
[eServiceCenter] clear instance
[eInit] - (35) CA handler
[eInit] - (35) CI Slots
[eInit] - (30) eActionMap
[eInit] - (22) Hdmi CEC driver
[eInit] - (21) input device driver
[eInit] - (20) AVSwitch Driver
[eInit] - (20) misc options
[eInit] - (20) RC Input layer
[eInit] - (20) UHF Modulator
[eInit] - (20) DVB-CI UI
[eInit] - (15) eWindowStyleManager
[eInit] - (10) gRC
[gRC] waiting for gRC thread shutdown
[gRC] thread has finished
[eInit] - (9) Font Render Class
[eInit] - (9) gLCD
[eInit] - (9) GFBDC
[eInit] - (8) graphics acceleration manager
[eInit] - (5) Tuxtxt
[eInit] - (1) Background File Eraser
[eInit] reached rl -1

**Comment by koivo** [comment]
We don't have an image 7.0.
